opt_out_usage
default_platform(:ios)

platform :ios do
  desc "Build and upload"
  lane :build_upload do
    build_release
    upload_deploygate
    telegram_notification
  end

  desc "Build the iOS app for release"
  lane :build_release do |options|
    app_identifier = ENV["APP_IDENTIFIER"]
    app_profile_name = ENV["APP_PROFILE_NAME"]
    team_id = ENV["TEAM_ID"]

    update_code_signing_settings(
      use_automatic_signing: false,
      targets: ["Miramax Fillms"],
      code_sign_identity: "iPhone Developer",
      bundle_identifier: app_identifier,
      profile_name: app_profile_name,
      team_id: team_id
    )

    gym(
      scheme: "Miramax Fillms",
      output_name: "Miramax Fillms.ipa",
      output_directory: "ipa",
      export_options: {
        method: "development",
        provisioningProfiles: {
          app_identifier => app_profile_name
        }
      },
      skip_package_dependencies_resolution: true,
      disable_package_automatic_updates: true,
      silent: true,
      clean: true
    )
  end

  desc "Upload ipa to DeployGate"
  lane :upload_deploygate do
    deploygate(
      api_token: ENV["DEPLOYGATE_API_KEY"],
      user: ENV["DEPLOYGATE_USERNAME"],
      ipa: lane_context[SharedValues::IPA_OUTPUT_PATH],
      message: "Build #{lane_context[SharedValues::BUILD_NUMBER]}"
    )
  end

  desc "Telegram notification"
  lane :telegram_notification do
    newly_uploaded_url = lane_context[SharedValues::DEPLOYGATE_URL]

    telegram(
      token: ENV["TELEGRAM_BOT_TOKEN"],
      chat_id: ENV["TELEGRAM_CHAT_ID"],
      text: "*Distribute ipa to Deploygate successfully* \n[#{newly_uploaded_url}](#{newly_uploaded_url})",
      parse_mode: "Markdown"
    )
  end

end
